spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5000}/${DB_NAME:postgres}?currentSchema=${DB_SCHEMA:auth}
    username: ${DB_USER:dummy}
    password: ${DB_PASSWORD:dummy}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://${ZIPKIN_LOG:localhost}:${ZIPKIN_LOG_PORT:9411}/
  sleuth:
    sampler:
      probability: 1


server:
  servlet:
    context-path: /auth
  port: ${AUTH_PORT:9000}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_REGISTRY:localhost}:${EUREKA_REGISTRY_PORT:7777}/eureka


