spring:
  cloud:
    config:
    #ALLOW CONTAINER ENV VARIABLE WIN TO CONFIGURATION
      allow-override: true
      override-none: true
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  security:
    user:
      name: ${CONFIG_SERVICE_USER:dummy}
      password: ${CONFIG_SERVICE_PASSWORD:dummy}

server:
  port: ${CONFIG_PORT:8888}

